name: CI

on:
  pull_request:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
    name: Check Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          miniforge-version: latest
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: pyopt-env

      - name: Install package
        shell: bash -l {0}
        run: |
        python -m pip install -e .[all]
        python setup.py build_ext -i

      - name: Test package
        shell: bash -l {0}
        run: python -m pytest
